Repository tektoncd-catalog/git-clone, pull requests merged in 2024-03, with the labels that each got.

#6 Bootstrap a CI using GitHub workflows
  .github/dependabot.yml
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  README.md
  image/git-init/.goreleaser.yml
Labels: size/L

#14 .github/workflow: fix build.yaml
  .github/workflows/build.yaml
Labels: size/XS

#4 Add OWNERS file in git-clone repo
  OWNERS
Labels: size/S
